/**
 * 
 */
package com.sca.common.message;

/**
 * 
 * @author subhash
 *
 */
public enum MessageAction {
	SEND_EMAIL, SAVE_METERING_DATA, SAVE_AMQ_ERROR_LOG, SAVE_USER_EVENT, SEND_MAIL_CAMPAIGN_PROJECT_QUEUE,
	SEND_MAIL_CAMPAIGN_USER_SUBSCRIBE, CREATE_DATA_COLLECTION_WORKFLOW, CREATE_DATA_PROCESSING_WORKFLOW
}
