--Services
INSERT INTO public.service (service_id, service_name, service_desc) VALUES
	(1, 'sca_eureka_service', 'SCA Eureka Service'),
	(2, 'sca_zuul_service', 'SCA Zuul Service'),
	(3, 'sca_audit_service', 'SCA Audit Service'),
	(4, 'sca_security_service', 'SCA Security Service'),
	(5, 'sca_scheduler_service', 'SCA Scheduler Service'),
	(6, 'sca_file_exchange_service', 'SCA File Exchange Service'),
	(7, 'sca_project_service', 'SCA Project Service'),
	(8, 'sca_order_service', 'SCA Order Service'),
	(9, 'sca_notification_service', 'SCA notification Service'),
	(10, 'sca_payment_service', 'SCA Payment Service');
	
--Entity Status at SCA
INSERT INTO public.entity_status (entity_status_id, "name", description) VALUES
	(1, 'Draft', null),
	(2, 'Successfully Submitted To FEMS', null),
	(3, 'Failed to Submit to FEMS', null);

--Languages supported	
INSERT INTO public.language(
	language_id, description, language_code)
	VALUES (1, 'English language', 'en-us');

--Country data
INSERT INTO public.country(country_id, name, display_name) VALUES (	1, 'United States', 'United States' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	2, 'Afghanistan', 'Afghanistan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	3, 'Albania', 'Albania' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	4, 'Algeria', 'Algeria' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	5, 'American Samoa', 'American Samoa' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	6, 'Andorra', 'Andorra' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	7, 'Angola', 'Angola' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	8, 'Anguilla', 'Anguilla' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	9, 'Antarctica', 'Antarctica' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	10, 'Antigua and Barbuda', 'Antigua and Barbuda' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	11, 'Argentina', 'Argentina' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	12, 'Armenia', 'Armenia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	13, 'Aruba', 'Aruba' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	14, 'Australia', 'Australia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	15, 'Austria', 'Austria' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	16, 'Azerbaijan', 'Azerbaijan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	17, 'Azores', 'Azores' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	18, 'Bahamas', 'Bahamas' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	19, 'Bahrain', 'Bahrain' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	20, 'Bangladesh', 'Bangladesh' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	21, 'Barbados', 'Barbados' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	22, 'Belarus', 'Belarus' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	23, 'Belgium', 'Belgium' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	24, 'Belize', 'Belize' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	25, 'Benin', 'Benin' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	26, 'Bermuda', 'Bermuda' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	27, 'Bhutan', 'Bhutan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	28, 'Bolivia', 'Bolivia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	29, 'Bosnia And Herzegowina', 'Bosnia And Herzegowina' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	30, 'Bosnia-Herzegovina', 'Bosnia-Herzegovina' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	31, 'Botswana', 'Botswana' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	32, 'Bouvet Island', 'Bouvet Island' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	33, 'Brazil', 'Brazil' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	34, 'British Indian Ocean Territory', 'British Indian Ocean Territory' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	35, 'British Virgin Islands', 'British Virgin Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	36, 'Brunei Darussalam', 'Brunei Darussalam' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	37, 'Bulgaria', 'Bulgaria' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	38, 'Burkina Faso', 'Burkina Faso' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	39, 'Burundi', 'Burundi' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	40, 'Cambodia', 'Cambodia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	41, 'Cameroon', 'Cameroon' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	42, 'Canada', 'Canada' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	43, 'Cape Verde', 'Cape Verde' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	44, 'Cayman Islands', 'Cayman Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	45, 'Central African Republic', 'Central African Republic' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	46, 'Chad', 'Chad' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	47, 'Chile', 'Chile' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	48, 'China', 'China' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	49, 'Christmas Island', 'Christmas Island' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	50, 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	51, 'Colombia', 'Colombia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	52, 'Comoros', 'Comoros' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	53, 'Congo', 'Congo' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	54, 'Congo, The Democratic Republic O', 'Congo, The Democratic Republic O' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	55, 'Cook Islands', 'Cook Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	56, 'Corsica', 'Corsica' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	57, 'Costa Rica', 'Costa Rica' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	58, 'Ivory Coast', 'Cote d` Ivoire (Ivory Coast)' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	59, 'Croatia', 'Croatia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	60, 'Cuba', 'Cuba' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	61, 'Cyprus', 'Cyprus' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	62, 'Czech Republic', 'Czech Republic' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	63, 'Denmark', 'Denmark' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	64, 'Djibouti', 'Djibouti' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	65, 'Dominica', 'Dominica' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	66, 'Dominican Republic', 'Dominican Republic' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	67, 'East Timor', 'East Timor' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	68, 'Ecuador', 'Ecuador' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	69, 'Egypt', 'Egypt' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	70, 'El Salvador', 'El Salvador' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	71, 'Equatorial Guinea', 'Equatorial Guinea' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	72, 'Eritrea', 'Eritrea' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	73, 'Estonia', 'Estonia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	74, 'Ethiopia', 'Ethiopia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	75, 'Falkland Islands', 'Falkland Islands (Malvinas)' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	76, 'Faroe Islands', 'Faroe Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	77, 'Fiji', 'Fiji' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	78, 'Finland', 'Finland' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	79, 'France (Includes Monaco)', 'France (Includes Monaco)' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	80, 'France, Metropolitan', 'France, Metropolitan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	81, 'French Guiana', 'French Guiana' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	82, 'French Polynesia', 'French Polynesia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	83, 'French Polynesia (Tahiti)', 'French Polynesia (Tahiti)' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	84, 'French Southern Territories', 'French Southern Territories' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	85, 'Gabon', 'Gabon' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	86, 'Gambia', 'Gambia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	87, 'Georgia', 'Georgia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	88, 'Germany', 'Germany' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	89, 'Ghana', 'Ghana' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	90, 'Gibraltar', 'Gibraltar' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	91, 'Great Britain', 'Great Britain' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	92, 'Greece', 'Greece' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	93, 'Greenland', 'Greenland' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	94, 'Grenada', 'Grenada' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	95, 'Guadeloupe', 'Guadeloupe' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	96, 'Guam', 'Guam' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	97, 'Guatemala', 'Guatemala' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	98, 'Guinea', 'Guinea' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	99, 'Guinea-Bissau', 'Guinea-Bissau' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	100, 'Guyana', 'Guyana' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	101, 'Haiti', 'Haiti' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	102, 'Heard And Mc Donald Islands', 'Heard And Mc Donald Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	103, 'Holy See (Vatican City State)', 'Holy See (Vatican City State)' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	104, 'Honduras', 'Honduras' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	105, 'Hong Kong', 'Hong Kong' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	106, 'Hungary', 'Hungary' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	107, 'Iceland', 'Iceland' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	108, 'India', 'India' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	109, 'Indonesia', 'Indonesia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	110, 'Iran', 'Iran' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	111, 'Iraq', 'Iraq' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	112, 'Ireland', 'Ireland' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	113, 'Ireland (Eire)', 'Ireland (Eire)' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	114, 'Israel', 'Israel' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	115, 'Italy', 'Italy' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	116, 'Jamaica', 'Jamaica' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	117, 'Japan', 'Japan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	118, 'Jordan', 'Jordan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	119, 'Kazakhstan', 'Kazakhstan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	120, 'Kenya', 'Kenya' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	121, 'Kiribati', 'Kiribati' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	122, 'Korea, Democratic People''S Repub', 'Korea, Democratic People''S Repub' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	123, 'Kuwait', 'Kuwait' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	124, 'Kyrgyzstan', 'Kyrgyzstan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	125, 'Laos', 'Laos' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	126, 'Latvia', 'Latvia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	127, 'Lebanon', 'Lebanon' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	128, 'Lesotho', 'Lesotho' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	129, 'Liberia', 'Liberia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	130, 'Libya', 'Libya' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	131, 'Liechtenstein', 'Liechtenstein' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	132, 'Lithuania', 'Lithuania' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	133, 'Luxembourg', 'Luxembourg' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	134, 'Macao', 'Macao' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	135, 'Macedonia', 'Macedonia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	136, 'Madagascar', 'Madagascar' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	137, 'Madeira Islands', 'Madeira Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	138, 'Malawi', 'Malawi' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	139, 'Malaysia', 'Malaysia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	140, 'Maldives', 'Maldives' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	141, 'Mali', 'Mali' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	142, 'Malta', 'Malta' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	143, 'Marshall Islands', 'Marshall Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	144, 'Martinique', 'Martinique' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	145, 'Mauritania', 'Mauritania' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	146, 'Mauritius', 'Mauritius' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	147, 'Mayotte', 'Mayotte' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	148, 'Mexico', 'Mexico' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	149, 'Micronesia, Federated States Of', 'Micronesia, Federated States Of' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	150, 'Moldova, Republic Of', 'Moldova, Republic Of' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	151, 'Monaco', 'Monaco' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	152, 'Mongolia', 'Mongolia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	153, 'Montserrat', 'Montserrat' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	154, 'Morocco', 'Morocco' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	155, 'Mozambique', 'Mozambique' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	156, 'Myanmar (Burma)', 'Myanmar (Burma)' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	157, 'Namibia', 'Namibia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	158, 'Nauru', 'Nauru' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	159, 'Nepal', 'Nepal' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	160, 'Netherlands', 'Netherlands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	161, 'Netherlands Antilles', 'Netherlands Antilles' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	162, 'New Caledonia', 'New Caledonia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	163, 'New Zealand', 'New Zealand' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	164, 'Nicaragua', 'Nicaragua' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	165, 'Niger', 'Niger' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	166, 'Nigeria', 'Nigeria' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	167, 'Niue', 'Niue' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	168, 'Norfolk Island', 'Norfolk Island' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	169, 'Northern Mariana Islands', 'Northern Mariana Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	170, 'Norway', 'Norway' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	171, 'Oman', 'Oman' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	172, 'Pakistan', 'Pakistan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	173, 'Palau', 'Palau' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	174, 'Palestinian Territory, Occupied', 'Palestinian Territory, Occupied' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	175, 'Panama', 'Panama' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	176, 'Papua New Guinea', 'Papua New Guinea' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	177, 'Paraguay', 'Paraguay' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	178, 'Peru', 'Peru' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	179, 'Philippines', 'Philippines' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	180, 'Pitcairn', 'Pitcairn' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	181, 'Poland', 'Poland' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	182, 'Portugal', 'Portugal' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	183, 'Puerto Rico', 'Puerto Rico' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	184, 'Qatar', 'Qatar' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	185, 'Reunion', 'Reunion' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	186, 'Romania', 'Romania' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	187, 'Russian Federation', 'Russian Federation' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	188, 'Rwanda', 'Rwanda' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	189, 'Saint Kitts And Nevis', 'Saint Kitts And Nevis' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	190, 'San Marino', 'San Marino' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	191, 'Sao Tome and Principe', 'Sao Tome and Principe' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	192, 'Saudi Arabia', 'Saudi Arabia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	193, 'Senegal', 'Senegal' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	194, 'Serbia-Montenegro', 'Serbia-Montenegro' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	195, 'Seychelles', 'Seychelles' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	196, 'Sierra Leone', 'Sierra Leone' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	197, 'Singapore', 'Singapore' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	198, 'Slovak Republic', 'Slovak Republic' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	199, 'Slovenia', 'Slovenia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	200, 'Solomon Islands', 'Solomon Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	201, 'Somalia', 'Somalia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	202, 'South Africa', 'South Africa' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	203, 'South Georgia And The South Sand', 'South Georgia And The South Sand' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	204, 'South Korea', 'South Korea' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	205, 'Spain', 'Spain' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	206, 'Sri Lanka', 'Sri Lanka' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	207, 'St. Christopher and Nevis', 'St. Christopher and Nevis' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	208, 'St. Helena', 'St. Helena' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	209, 'St. Lucia', 'St. Lucia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	210, 'St. Pierre and Miquelon', 'St. Pierre and Miquelon' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	211, 'St. Vincent and the Grenadines', 'St. Vincent and the Grenadines' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	212, 'Sudan', 'Sudan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	213, 'Suriname', 'Suriname' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	214, 'Svalbard And Jan Mayen Islands', 'Svalbard And Jan Mayen Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	215, 'Swaziland', 'Swaziland' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	216, 'Sweden', 'Sweden' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	217, 'Switzerland', 'Switzerland' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	218, 'Syrian Arab Republic', 'Syrian Arab Republic' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	219, 'Taiwan', 'Taiwan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	220, 'Tajikistan', 'Tajikistan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	221, 'Tanzania', 'Tanzania' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	222, 'Thailand', 'Thailand' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	223, 'Togo', 'Togo' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	224, 'Tokelau', 'Tokelau' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	225, 'Tonga', 'Tonga' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	226, 'Trinidad and Tobago', 'Trinidad and Tobago' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	227, 'Tristan da Cunha', 'Tristan da Cunha' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	228, 'Tunisia', 'Tunisia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	229, 'Turkey', 'Turkey' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	230, 'Turkmenistan', 'Turkmenistan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	231, 'Turks and Caicos Islands', 'Turks and Caicos Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	232, 'Tuvalu', 'Tuvalu' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	233, 'Uganda', 'Uganda' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	234, 'Ukraine', 'Ukraine' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	235, 'United Arab Emirates', 'United Arab Emirates' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	236, 'United Kingdom', 'United Kingdom' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	237, 'United States', 'United States' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	238, 'Uruguay', 'Uruguay' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	239, 'Uzbekistan', 'Uzbekistan' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	240, 'Vanuatu', 'Vanuatu' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	241, 'Vatican City', 'Vatican City' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	242, 'Venezuela', 'Venezuela' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	243, 'Vietnam', 'Vietnam' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	244, 'Virgin Islands (U.S.)', 'Virgin Islands (U.S.)' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	245, 'Wallis and Furuna Islands', 'Wallis and Furuna Islands' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	246, 'Western Sahara', 'Western Sahara' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	247, 'Western Samoa', 'Western Samoa' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	248, 'Yemen', 'Yemen' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	249, 'Yugoslavia', 'Yugoslavia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	250, 'Zaire', 'Zaire' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	251, 'Zambia', 'Zambia' );
INSERT INTO public.country(country_id, name, display_name) VALUES (	252, 'Zimbabwe', 'Zimbabwe' );

--State data
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (1, 'Alabama','Alabama',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (2, 'Alaska','Alaska',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (3, 'American Samoa','American Samoa',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (4, 'Arizona','Arizona',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (5, 'California','California',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (6, 'Connecticut','Connecticut',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (7, 'Delaware','Delaware',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (8, 'Georgia','Georgia',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (9, 'Hawaii','Hawaii',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (10, 'Illinois','Illinois',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (11, 'Iowa','Iowa',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (12, 'Kentucky','Kentucky',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (13, 'Maine','Maine',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (14, 'Marshall Islands','Marshall Islands',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (15, 'Massachusetts','Massachusetts',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (16, 'Micronesia','Micronesia',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (17, 'Military Europe','Military Europe/ME/Canada',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (18, 'Minnesota','Minnesota',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (19, 'Missouri','Missouri',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (20, 'Nebraska','Nebraska',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (21, 'New Hampshire','New Hampshire',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (22, 'New Mexico','New Mexico',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (23, 'North Carolina','North Carolina',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (24, 'Ohio','Ohio',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (25, 'Oregon','Oregon',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (26, 'Pennsylvania','Pennsylvania',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (27, 'Rhode Island','Rhode Island',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (28, 'South Dakota','South Dakota',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (29, 'Texas','Texas',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (30, 'Vermont','Vermont',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (31, 'Virginia','Virginia',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (32, 'West Virginia','West Virginia',1);
INSERT INTO public.state(state_id, name, display_name, country_id) VALUES (33, 'Wyoming','Wyoming',1);

--Credit Card Type data
INSERT INTO public.credit_card_type(credit_card_type_id, name, display_name) VALUES (1, 'Discover', 'Discover');
INSERT INTO public.credit_card_type(credit_card_type_id, name, display_name) VALUES (2, 'American Express', 'American Express');
INSERT INTO public.credit_card_type(credit_card_type_id, name, display_name) VALUES (3, 'Visa', 'Visa');
INSERT INTO public.credit_card_type(credit_card_type_id, name, display_name) VALUES (4, 'MasterCard', 'MasterCard');

--Shipping Method data
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (1, 'FedEx Saver', 'FedEx Saver');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (2, 'FedEx 2nd Day', 'FedEx 2nd Day');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (3, 'FedEx Standard Over Night', 'FedEx Standard Over Night');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (4, 'FedEx Priority Over Night', 'FedEx Priority Over Night');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (5, 'UPS Next Day AM', 'UPS Next Day AM');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (6, 'UPS Next Day', 'UPS Next Day');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (7, 'UPS Next Day Saturday Delivery', 'UPS Next Day Saturday Delivery');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (8, 'UPS Next Day Saver', 'UPS Next Day Saver');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (9, 'UPS 2nd Day AM', 'UPS 2nd Day AM');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (10, 'UPS 2nd Day Delivery', 'UPS 2nd Day Delivery');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (11, 'UPS 3rd Day', 'UPS 3rd Day');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (12, 'UPS Ground (Give it a good 5-7 business days)', 'UPS Ground (Give it a good 5-7 business days)');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (14, 'Will Call (only available for certain products)', 'Will Call (only available for certain products)');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (16, 'FedEx International Economy', 'FedEx International Economy');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (17, 'Driver option', 'Driver option');
INSERT INTO public.shipping_method(shipping_method_id, name, display_name) VALUES (24, 'DHL', 'DHL');

--Address Type
INSERT INTO public.address_type(address_type_id, description, name) VALUES (1, 'Shipping Address', 'Shipping Address' );
INSERT INTO public.address_type(address_type_id, description, name) VALUES (2, 'Billing Address', 'Billing Address' );
INSERT INTO public.address_type(address_type_id, description, name) VALUES (3, 'Designer Address', 'Designer Address' );
INSERT INTO public.address_type(address_type_id, description, name) VALUES (4, 'Other Address', 'Other Address' );
